# Generated by Django 4.0.6 on 2022-07-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
