# Generated by Django 4.0.6 on 2022-07-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invest', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=10)),
                ('description', models.TextField(null=True)),
                ('history', models.TextField(null=True)),
            ],
        ),
    ]
