# Generated by Django 4.0.6 on 2022-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='stock_name',
            field=models.ManyToManyField(to='invest.stock'),
        ),
    ]
