# Generated by Django 4.0.6 on 2022-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_stock_company_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_long_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
