# Generated by Django 4.0.6 on 2022-07-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_stock_stock_long_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stock_name',
            new_name='stock_names',
        ),
    ]
