# Generated by Django 4.0.6 on 2022-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_rename_stock_name_company_stock_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('definition', models.CharField(max_length=1000)),
            ],
        ),
    ]
