# Generated by Django 4.0.6 on 2022-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_indicators_short_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicators',
            new_name='Indicator',
        ),
    ]
