# Generated by Django 4.0.6 on 2022-07-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stock_names',
        ),
        migrations.AddField(
            model_name='company',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invest.stock'),
        ),
    ]
