# Generated by Django 4.0.6 on 2022-07-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0011_remove_company_stock_names_company_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='indicator',
        ),
        migrations.AddField(
            model_name='strategy',
            name='indicator',
            field=models.ManyToManyField(to='invest.indicator'),
        ),
    ]
