# Generated by Django 4.0.6 on 2022-07-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0012_remove_strategy_indicator_strategy_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
